inherit_from: .rubocop_todo.yml

AllCops:
    EnabledByDefault: true
    Exclude:
        - 'vendor/bundle/**/*'
        - 'rails_generators/gruff/**/*'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
