inherit_from: .rubocop_todo.yml
require: rubocop-performance

AllCops:
    EnabledByDefault: true
    TargetRubyVersion: 2.4
    Exclude:
        - 'vendor/bundle/**/*'
        - 'rails_generators/gruff/**/*'

Gemspec/OrderedDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: true

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ClassStructure:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Lint/AssignmentInCondition:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: true

Style/Encoding:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/IfUnlessModifier:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: false
