language: ruby
sudo: false
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "2.1"
  - "2.2"
  - jruby-18mode
  - jruby-19mode
  - jruby-20mode
  - jruby-head
  - rbx
  - rbx-2
notifications:
  email:
    - uwe@kubosch.no
