language: ruby
dist: bionic
cache: bundler

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - jruby-9.2.14.0

jobs:
  include:
    - name: 'Lint'
      rvm: 2.4
      script: bundle exec rubocop

addons:
  apt:
    packages:
      - gsfonts
      - ghostscript
