language: ruby
cache: bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-1.7.26
  - jruby-9.0.5.0
  - jruby-9.1.9.0
  - jruby-head

jobs:
  include:
    - name: 'Lint'
      rvm: 2.3
      script: bundle exec rubocop

addons:
  apt:
    packages:
      - gsfonts
      - ghostscript
